dev-protocol/protocol-v2

contracts/interface/IProperty.sol, contracts/interface/IPropertyFactory.sol, contracts/src/property/Property.sol, contracts/src/property/PropertyFactory.sol, test/property/property-factory.ts, test/property/property.ts
Fixes #39 .
---
By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/protocol/blob/main/CODE_OF_CONDUCT.md) 🖖
=> Moved `ChangeAuthor`, `ChangeName` and `ChangeSymbol` events from PropertyFactory to Property

contracts/test/common/proxy/UpgradeabilityBase.sol, contracts/test/common/proxy/UpgradeabilityDifferentContractName.sol, contracts/test/common/proxy/UpgradeabilityDifferentContractNameAndOrder.sol, test/common/proxy/upgradeability.ts, test/dev/dev-minter.ts, test/test-lib/instance.ts
Understand and test the upgradeability specifications.
We can check under what conditions the upgrade possibility does not collapse.
Fixes # .
---
By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/protocol/blob/main/CODE_OF_CONDUCT.md) 🖖
=> Test for upgradeability

contracts/interface/ISTokensManager.sol, contracts/src/s-token/STokensManager.sol, test/lockup/lockup-s-token.ts, test/s-token/s-token-manager.ts
change func name at STokensManager.
=> update func name

contracts/src/lockup/Lockup.sol, test/lockup/lockup-s-token.ts
[ Please write here what changes this pull request ]
add new event Withdrew in Lockup and emit it in withdrawByPosition function
[ Please write here about why needs this change ]
Fixes # .
---
By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/protocol/blob/main/CODE_OF_CONDUCT.md) 🖖
=> Add event withdrew in lockup

contracts/interface/IWithdraw.sol, contracts/src/withdraw/Withdraw.sol, test/withdraw/withdraw.ts
=> Delete unnecessary func

contracts/interface/IMarket.sol, contracts/interface/IMarketBehavior.sol, contracts/interface/IPropertyFactory.sol, contracts/src/market/Market.sol, contracts/src/property/PropertyFactory.sol, contracts/test/market/MarketTest1.sol, contracts/test/market/MarketTest2.sol, contracts/test/market/MarketTest3.sol, test/market/market.ts, test/property/property-factory.ts, test/withdraw/withdraw.ts
change Market authenticate args type
There were too many arguments.
=> change Market authenticate args type

contracts/interface/IMarketFactory.sol, contracts/interface/IMetricsFactory.sol, contracts/src/lockup/Lockup.sol, contracts/src/market/MarketFactory.sol, contracts/src/metrics/MetricsFactory.sol, test/market/market-factory.ts, test/metrics/metrics-factory.ts
[ Please write here what changes this pull request ]
update MarketFactory.Create event, MetricsFactory.Create event and Destroy event
[ Please write here about why needs this change ]
Fixes # .
---
By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/protocol/blob/main/CODE_OF_CONDUCT.md) 🖖
=> Modify events

contracts/interface/IMarket.sol, contracts/interface/IMarketBehavior.sol, contracts/src/market/Market.sol, contracts/test/market/MarketTest1.sol, contracts/test/market/MarketTest2.sol, contracts/test/market/MarketTest3.sol, test/market/market.ts
add name function to market behavior
for get market name from onchain
=> add name function

contracts/interface/IMarketBehavior.sol, contracts/src/market/Market.sol, contracts/src/market/MarketFactory.sol, contracts/test/market/MarketTest1.sol, contracts/test/market/MarketTest2.sol, contracts/test/market/MarketTest3.sol, test/market/market-factory.ts, test/market/market.ts, test/property/property-factory.ts, test/test-lib/instance.ts, test/withdraw/withdraw.ts
=> update behavior interface

contracts/test/treasury/TreasuryTest.sol, test/test-lib/instance.ts
Added proxy support for tresuary.
=> tresuary proxy

contracts/src/dev/Dev.sol, contracts/src/dev/DevMinter.sol, contracts/src/lockup/Lockup.sol, contracts/src/withdraw/Withdraw.sol
delete unnecessary comment
unnecessary
=> delete unnecessary comment

contracts/interface/ILockup.sol, contracts/src/lockup/Lockup.sol, contracts/src/market/MarketFactory.sol, contracts/src/metrics/MetricsFactory.sol, contracts/src/policy/Policy1.sol, contracts/src/property/Property.sol, contracts/src/s-token/STokensManager.sol, contracts/src/withdraw/Withdraw.sol
change private vars sort
upgradable
=> change private vars sort

test/s-token/s-token-manager.ts
=> update  broken test case

contracts/interface/IAddressRegistry.sol, contracts/interface/IMarketBehavior.sol, contracts/interface/IProperty.sol, contracts/interface/IPropertyFactory.sol, contracts/src/common/registry/AddressRegistry.sol, contracts/src/property/Property.sol, contracts/src/property/PropertyFactory.sol, contracts/test/market/MarketTest1.sol, contracts/test/market/MarketTest2.sol, contracts/test/market/MarketTest3.sol, package.json, truffle-config.arbitrum.js, yarn.lock
change truffle setting (and more)
=> prepare deploy

migrations/update/1_redeploy-market-factory.ts
=> update deploy script

package.json, renovate.json
=> fix versions

test/market/market-factory.ts
=> delete unnecessary modifies

test/dev/dev-arbitrum.ts, test/dev/dev-bridge.ts, test/dev/dev-polygon.ts, test/dev/dev.ts, test/test-lib/utils/snapshot.ts
=> Improve test speed test/dev

.github/workflows/nodejs.yml
test/s-token will be not checked after PRs, so I updated workflows.
=> add test-sToken into workflows

test/lockup/lockup-s-token-common.ts, test/lockup/lockup-s-token-scenario.ts, test/lockup/lockup-s-token.ts
=> Improve test lockup s token.ts

test/lockup/lockup.ts
=> improve test speed of lockup.ts

test/s-token/s-token-manager.ts
=> merge s-token-manager.ts from get-property-of-author

package.json, test/s-token/s-token-manager.ts, yarn.lock
=> update dotenv to 14.3.2

contracts/interface/IProperty.sol, contracts/interface/IPropertyFactory.sol, contracts/src/property/Property.sol, contracts/src/property/PropertyFactory.sol, migrations/set-property-addresses/1_set-property-addresses.ts, migrations/update/1_update-property-factory.ts, test/property/property-factory.ts, test/property/property.ts, test/s-token/s-token-manager.ts, test/withdraw/withdraw-scenario.ts, test/withdraw/withdraw.ts, truffle-config.js
=> get property of author

contracts/interface/ISTokensManager.sol, contracts/interface/ITokenURIDescriptor.sol, contracts/src/s-token/STokensManager.sol, contracts/test/stoken/TokenURIDescriptorTest.sol, migrations/grant-roll/1_grant-roll-dev-polygon.ts, migrations/update/1_update-s-token-manager.ts, test/s-token/s-token-manager.ts, test/test-lib/instance.ts
=> Description

contracts/src/s-token/STokensManager.sol, migrations/grant-roll/1_grant-roll-dev-polygon.ts
=> Change safemint to mint

contracts/src/lockup/Lockup.sol
Follow https://github.com/dev-protocol/protocol/pull/1238
=> follow https://github.com/dev-protocol/protocol/pull/1238

contracts/interface/IProperty.sol
adding transfer interface for property token
=> [add]: transfer interface

contracts/src/s-token/STokensManager.sol
merge after 
https://github.com/dev-protocol/protocol-v2/pull/535
=> Fix order of `royaltyOf` variable

.openzeppelin/polygon-mumbai.json, .openzeppelin/polygon.json, .openzeppelin/unknown-42161.json, contracts/src/s-token/STokensManager.sol
=> fix name & descrip dependecy on tokenUriImage & new implementation (#549)
